INSERT INTO SELLER (SELLER_NAME) VALUES ('ALEXANDRE CONTINES');
INSERT INTO SELLER (SELLER_NAME) VALUES ('AUGUSTO FONSECA');

INSERT INTO SALE (SALED_AT, SALE_VALUE, SELLER_ID) VALUES (CURRENT_DATE, 20.98, 1);
INSERT INTO SALE (SALED_AT, SALE_VALUE, SELLER_ID) VALUES (CURRENT_DATE, 19.99, 2);
INSERT INTO SALE (SALED_AT, SALE_VALUE, SELLER_ID) VALUES (CURRENT_DATE, 28.98, 1);
INSERT INTO SALE (SALED_AT, SALE_VALUE, SELLER_ID) VALUES (CURRENT_DATE, 89.99, 2);