DROP TABLE IF EXISTS SELLER;

CREATE TABLE SELLER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SELLER_NAME VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS SALE;

CREATE TABLE SALE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SALED_AT DATE NOT NULL,
    SELLER_ID INT NOT NULL,
    SALE_VALUE DOUBLE NOT NULL,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID)
);